### ISSUE TITLE
Replace max hop count and total hop count with remaining hop count?

### ISSUE THREAD

**Issue by mickeyspiegel** [p4lang/p4-applications#14]
By replacing max hop count and total hop count with remaining hop count, we can save one byte in the INT header.

- Source sets initial value of remaining hop count
- Every hop that adds INT metadata decrements the remaining hop count by 1
- When remaining hop count reaches 0, the INT metadata stack is full and the E bit must be set to 1

A device parsing the INT metadata stack uses the length from the appropriate INT shim header to determine when it reaches the end of the INT metadata stack:
- metadata stack size = 'length' * 4 - [total fixed header sizes]

**Comment by mhira1** [comment]
This is addressed by Mickey's commit 19295e59b8adafd825c02dd4735ebf9363bf7a68
