### ISSUE TITLE
Checksum Complement Metadata

### ISSUE THREAD

**Issue by talmi** [p4lang/p4-applications#16]
When INT is encapsulated over a protocol that includes an L4 header, e.g., VXLAN-GPE or Geneve, the L4 header includes a Checksum field. In this case, each INT switch needs to update the L4 Checksum field based on the INT fields that were added/modified. 

The challenge is that these INT fields may be significantly deeper into the packet than the L4 Checksum, making it difficult for sequential hardware processing when these fields are added/modified inflight.

The proposal is to add a <Checksum Complement> metadata, which can be used to guarantee a checksum neutral update when the INT fields are added/modified.

A similar approach is used in PTP (IEEE 1588), NTP (RFC 7821), and IOAM (draft-ietf-ippm-ioam-data).

**Comment by mhira1** [comment]
Tal, the IOAM draft allows for both pre-allocated headers and incremental headers. In the case of pre-allocated headers, each hop writes deeper into the packet, so the metadata being inserted can be arbitrarily deeper into the packet from the L4 checksum.

The current INT data plane specification only uses incremental (hop-by-hop) header allocation. Every transit hop adds its metadata to the top of the stack, but yes there may still be some benefits to inserting "checksum neutral" metadata compared to over-writing L4 checksum.

Let's discuss this at the next working group meeting. Can you or someone on your behalf from Marvell present your proposal?

**Comment by jafingerhut** [comment]
I do not have a specific suggestion for a header format, but if the 'checksum neutral' part was a 16-bit field, and in a fixed position near the beginning of the header, then implementations should not need to reach arbitrarily deep into the packet to read, update, and write it back.

The PSA does specify an InternetChecksum extern with both 'add' and 'subtract' methods that can be used to incrementally update a packet received with a correct UDP checksum, and it should have all you need for this kind of thing, too.

**Comment by jklr** [comment]
@talmi can you pls comment on the sensitivity of placement of the checksum complement? As discussed in the prev meeting, does it need to come after all modified/added fields at each hop device? Two things to consider:
1) it may need to take the last INT instruction bit, e.g., the 16th bit in the current spec, and the 32th bit if we ever extend the instruction bits to 32b.
2) INT Tail header comes after the INT stack added by the INT Source device. Can the chip architecture handle the additional 4B added after the checksum complement? 
Thanks.

**Comment by talmi** [comment]
In my opinion the 4-byte tail after the checksum complement should not be a problem.

**Comment by jklr** [comment]
Closing as this issue has been addressed in PR #25.
