### ISSUE TITLE
Implement egress MTU checks in INT transit P4 program in dataplane specification

### ISSUE THREAD

**Issue by mhira1** [p4lang/p4-applications#17]
P4 program in section 6 of the dataplane specification needs to be modified to implement egress MTU validations as per recent [edits](https://github.com/p4lang/p4-applications/commit/51a0b5b57d978a95891f75e02e45435d07b5a85b) to the spec. In particular, Int_egress needs to be aware of egress link MTU. If adding metadata will cause egress link MTU to be exceeded, no metadata should be added to the packet and newly defined M bit in the INT header must be set.

**Comment by jklr** [comment]
Resolved in PR #34.
