### ISSUE TITLE
Missing hop in INT example for TCP/IP

### ISSUE THREAD

**Issue by bapinetro** [p4lang/p4-applications#28]
The TCP/IP example (Line 943) in the spec appears to be  missing a hop. The other examples contain metadata for three hops each.

INT Metadata Header and Metadata Stack:
`
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |  Ver  |Rep|C|E|M|     Reserved      | HopML=2 |RemainingHopC=6|
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0|           Reserved            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                           sw id of hop2                       |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                      queue occupancy of hop2                  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                           sw id of hop1                       |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                      queue occupancy of hop1                  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
`

**Comment by mhira1** [comment]
Thanks for catching this Bapi. I am making some editorial changes, will fix this as part of those changes.

**Comment by mhira1** [comment]
Bapi, as I was reading the spec thoroughly and making editorial changes, I noticed a subtle point - this is not an error. INT over TCP example assumes that switch1 is INT source and switch3 is INT sink. Packet received at INT sink switch3 is shown.

INT over encapsulation originating at Host1 (VXLAN/GENEVE) example assumes Host1 is INT source, Host2 is INT sink. Thus the INT sink in this case sees all 3 previous transit INT hops.

I did make this difference clear in the preamble to the examples. This is part of editorial changes I am sending as a PR shortly. Please review once I send out the PR and close this issue if things look ok.
