### ISSUE TITLE
Update fixed header size in INT.mdk

### ISSUE THREAD

**Issue by ghost** [p4lang/p4-applications#70]
The fixed header size used to be 12 bytes and with the addition of Domain Specific ID (2 bytes) ad Domain Specific Instruction (2 bytes), the new fixed header size is 12+4= 16 bytes. 
Section 5.7 in INT.mdk mentions the INT fixed header size to be 12 bytes and would need to be updated.

**Comment by jklr** [comment]
Thanks for the review!
We've recently changed the meaning of shim header length. It used to include itself (4B) but not any more, canceling out the additional 4B added for Domain extension. Hence 12B is correct.
